name: Migration Test

on:
  push:
    paths:
      - 'object/migrator**'
  pull_request:
    paths:
      - 'object/migrator**'

jobs:

  migration-test:
    name: Migration-Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: casdoor
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: download casdoor-master-latest
        run: |
          sudo apt update
          sudo apt install git
          sudo apt install net-tools
          sudo apt install execline
          sudo mkdir tmp
          cd tmp
          sudo git clone https://github.com/casdoor/casdoor.git      
          cd ..
      - name: start casdoor-master-latest
        run: |
          sudo nohup go run main.go &
        working-directory: ./tmp/casdoor
      - name: stop casdoor-master-latest
        run: |
          sudo sleep 2m
          echo 'kill 前'
          sudo netstat -nltp
          sudo kill -9 `sudo netstat -anltp | grep 8000 | awk '{print $7}' | cut -d / -f 1`
          echo 'kill 后'
          sudo netstat -nltp
      - name: back start
        run: |
          echo '启动前'
          sudo netstat -nltp
          nohup go run ./main.go &
          sudo sleep 2m
          echo '启动后'
          sudo netstat -nltp
        working-directory: ./
      - name: sleep 2m
        run: sudo sleep 2m
      - name: test port-8000
        run: |
          sudo export casdoor_pid=`sudo netstat -anltp | grep 8000 | awk '{print $7}' | cut -d / -f 1`
          if [ $casdoor_pid="" ];then exit 1;fi;
          echo 'migrate-test pass!!!'